/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/core/coredemo': RouteRecordInfo<'/core/coredemo', '/core/coredemo', Record<never, never>, Record<never, never>>,
    '/core/coredemo/element/': RouteRecordInfo<'/core/coredemo/element/', '/core/coredemo/element', Record<never, never>, Record<never, never>>,
    '/core/coredemo/element2/': RouteRecordInfo<'/core/coredemo/element2/', '/core/coredemo/element2', Record<never, never>, Record<never, never>>,
    '/core/coredemo2': RouteRecordInfo<'/core/coredemo2', '/core/coredemo2', Record<never, never>, Record<never, never>>,
    '/core/coredemo2/element/': RouteRecordInfo<'/core/coredemo2/element/', '/core/coredemo2/element', Record<never, never>, Record<never, never>>,
    '/core/coredemo2/element2/': RouteRecordInfo<'/core/coredemo2/element2/', '/core/coredemo2/element2', Record<never, never>, Record<never, never>>,
    '/exam/coredemo': RouteRecordInfo<'/exam/coredemo', '/exam/coredemo', Record<never, never>, Record<never, never>>,
    '/exam/coredemo/element/': RouteRecordInfo<'/exam/coredemo/element/', '/exam/coredemo/element', Record<never, never>, Record<never, never>>,
    '/exam/coredemo/element2/': RouteRecordInfo<'/exam/coredemo/element2/', '/exam/coredemo/element2', Record<never, never>, Record<never, never>>,
    '/exam/coredemo2': RouteRecordInfo<'/exam/coredemo2', '/exam/coredemo2', Record<never, never>, Record<never, never>>,
    '/exam/coredemo2/element/': RouteRecordInfo<'/exam/coredemo2/element/', '/exam/coredemo2/element', Record<never, never>, Record<never, never>>,
    '/exam/coredemo2/element2/': RouteRecordInfo<'/exam/coredemo2/element2/', '/exam/coredemo2/element2', Record<never, never>, Record<never, never>>,
  }
}
