/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//coredemo': RouteRecordInfo<'//coredemo', '/coredemo', Record<never, never>, Record<never, never>>,
    '//coredemo/element/': RouteRecordInfo<'//coredemo/element/', '/coredemo/element', Record<never, never>, Record<never, never>>,
    '//coredemo/element2/': RouteRecordInfo<'//coredemo/element2/', '/coredemo/element2', Record<never, never>, Record<never, never>>,
    '//coredemo2': RouteRecordInfo<'//coredemo2', '/coredemo2', Record<never, never>, Record<never, never>>,
    '//coredemo2/element/': RouteRecordInfo<'//coredemo2/element/', '/coredemo2/element', Record<never, never>, Record<never, never>>,
    '//coredemo2/element2/': RouteRecordInfo<'//coredemo2/element2/', '/coredemo2/element2', Record<never, never>, Record<never, never>>,
  }
}
